image: node:7

stages:
  - test
  - deploy

before_script:
  - npm install

test:
  script:
    - npm run test
    - npm run build

publish:
  stage: deploy
  only:
    - master
  script:
    - $(npm bin)/semantic-release-gitlab
